### ISSUE TITLE
Bring in OWASP for security document

### ISSUE THREAD

**Issue by ScreamingDev** [ataylorme/WordPress-Hosting-Best-Practices-Documentation#10]
Suggestion:

OWASP has a site for WordPress with lots of information (maybe partly outdated):

https://www.owasp.org/index.php/OWASP_Wordpress_Security_Implementation_Guideline

As the security site is still empty you may want to bring in some of those contents.

**Comment by ataylorme** [comment]
Thanks for the link @ScreamingDev - I haven't seen this resource before.

**Comment by ataylorme** [comment]
@ScreamingDev I think rather than bringing this all in we can link to it as an additional resource in the security section, which had a lot more content added in #16 

See #20 for the PR

**Comment by ataylorme** [comment]
@ScreamingDev thanks for the suggestion but I don't think we will be including this for now. See the details in #20.

**Comment by ScreamingDev** [comment]
Nice. Link is enough, right. 
As this is almost open source don't we want to enhance the owasp or maintain a wp entry there?  Feels better than everyone doing their own documents.
Dunno if this fits to the goal of this repo but I am sure you can tell :)

**Comment by ataylorme** [comment]
I agree open source is about helping all parties. I requested access to make edits about 2 weeks ago and haven't heard anything. If that changes I can suggest changes but if the docs stay as-is we don't feel comfortable linking to outdated materials.
