### ISSUE TITLE
Required PHP modules and utilities outdated

### ISSUE THREAD

**Issue by ottok** [ataylorme/WordPress-Hosting-Best-Practices-Documentation#32]
The list at https://github.com/ataylorme/WordPress-Hosting-Best-Practices-Documentation/blob/master/server-environment/server-environment.md would be much more useful if it included some motivations _why_ something is needed. For example [mcrypt has been deprecated in PHP 7.1](http://php.net/manual/en/migration71.deprecated.php) in favour of OpenSSL. I am pretty sure nothing in WordPress or plugins has been using it for years. Why recommend it here?

Also the list would be great if each item was a link to the home page of that PHP module or software library. Some of the modules mentioned I cannot find at all (filter, fileinfo, mod_xml). I suspect they are outdated old names for something that does not exist as a PHP module anymore..?

**Comment by ataylorme** [comment]
Hi @ottok,
We took an inventory of which PHP modules WordPress could be using.

mcrypt, even though it has been deprecated in newer versions of PHP, is still in use when WordPress is when running on older PHP versions or when other libraries are missing.

See [`wp-includes/random_compat/random.php`](https://github.com/WordPress/wordpress-develop/blob/4.9.6/src/wp-includes/random_compat/random.php#L57:L79) and [`wp-includes/random_compat/random_bytes_mcrypt.php`](https://github.com/WordPress/wordpress-develop/blob/4.9.6/src/wp-includes/random_compat/random_bytes_mcrypt.php#L29:L42).

These docs aren't just recommendations for hosts with newer PHP versions but for all hosts, even those with older versions.

We do, however, want to encourage hosts to adopt newer PHP versions. If you would like to contribute a pull request splitting the list into a PHP 7+ and 5.x list would be great. That way hosts would be able to see what they should be installed if they are running newer PHP versions.

**Comment by ottok** [comment]
The same issue was reported in https://meta.trac.wordpress.org/ticket/3632#comment:9

Since we now have https://make.wordpress.org/hosting/handbook/handbook/server-environment/#php-extensions this entire repository seems obsolete and this issue can be closed.
